apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: quiz-roulette-question-bank-graphql
  name: quiz-roulette-question-bank-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quiz-roulette-question-bank-graphql
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: quiz-roulette-question-bank-graphql
        logs_selector: backend
    spec:
      containers:
        - image: quizroulette/question-bank-graphql:v2.2.2
          name: quiz-roulette-question-bank-graphql
          ports:
            - containerPort: 34000
          resources: {}
      restartPolicy: Always
status: {}
