apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-roulette-spring-cloud-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quiz-roulette-spring-cloud-api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: quiz-roulette-spring-cloud-api-gateway
    spec:
      containers:
        - image: quizroulette/spring-cloud-api-gateway:v1.0.0
          name: quiz-roulette-spring-cloud-api-gateway
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: ROUTE_QUESTION_BANK_GRAPHQL
              #value: "http://quiz-roulette-question-bank-graphql:34000"
              value: "http://quiz-roulette-question-bank-graphql.default.svc.cluster.local:34000"
            - name: JAVA_OPTS
              value: "-Dserver.port=8080"
      restartPolicy: Always
status: {}
