apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-service-deployment
  labels:
    app: legacy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-service
  template:
    metadata:
      labels:
        app: legacy-service
        logs_selector: backend
    spec:
      containers:
      - name: legacy-service
        image: quizroulette/legacy-service:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: QUIZ-ROULETTE_QUESTION-BANK-URL
          value: "http://quiz-roulette-question-bank-graphql:34000/graphql"
        - name: QUIZ-ROULETTE_USER-SERVICE-URL
          value: "http://user-service-service:8080"
        - name: QUIZ-ROULETTE_QUIZ-LOG-SERVICE-URL
          value: "http://quiz-transaction-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: legacy-service-service
spec:
  selector:
    app: legacy-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
